config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, except: [:destroy]
  get "users/:id/favorites", to: "users#favorites"

  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

    belongs_to :user
    belongs_to :picture

end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :title, :image, presence: true
    validates :content, length: { in: 1..140 }

    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user

    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :pictures
  has_many :favorites, dependent: :destroy

  mount_uploader :user_image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

    # ログインしていないユーザによるアクセスを禁ずる
    def authenticate_user
      if current_user == nil
        redirect_to new_session_path, notice: "ログインが必要です"
      end
    end

    #ログインユーザーによるアクセスを禁ずる
    def forbid_login_user
      if current_user
        redirect_to user_path(current_user.id), notice: "すでにログイン中です"
      end
    end

    # ログインユーザのみ投稿の編集・削除許可
    def ensure_correct_user
      if current_user.id != @picture.user_id
        redirect_to pictures_path, notice: "権限がありません"
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit,:update,:destroy]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if @picture.save
        ContactMailer.contact_mail(@picture).deliver
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update,:show]
  before_action :authenticate_user, only: [:edit,:update,:show,:index, :favorites]
  before_action :forbid_login_user, only: [:new,:create]
  before_action :ensure_login_user, only: [:edit,:update]

  def index
    @users = User.all
  end

  def edit
  end

  def new
   @user = User.new
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザプロフィールが編集されました'
    else
      render "edit"
    end
  end

  def create
   @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
     else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def favorites
    @user = User.find_by(id: params[:id])
    @favorites = Favorite.where(user_id: @user.id)
  end

  private
  def set_user
     @user = User.find(params[:id])
  end

  def ensure_login_user
    if current_user.id != params[:id].to_i
      redirect_to pictures_path, notice: "権限がありません"
    end
  end

  def user_params
     params.require(:user).permit(:name,:email,:password,:password_confirmation,:user_image,:user_image_cache)
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
       @current_user ||= User.find_by(id: session[:user_id]) 
    end
    
    def logged_in?
        current_user.present?
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramclone</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <ul>
      <% if logged_in? %>
        <li><%= link_to "新規投稿", new_picture_path %></li>
        <li><%= link_to "投稿一覧", pictures_path %></li>
        <li><%= link_to 'ユーザ一覧', users_path %></li>
        <li><%= link_to "#{current_user.name}", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <li><%= link_to "サインイン", new_user_path %></li>
        <li><%= link_to "ログイン", new_session_path %></li>
      <% end %>
    </ul>
  </header>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "") %> 件のエラーが発生しました:</h2>
      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :picture_content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
    <%= image_tag(@picture.image.url, size: "500x200") if @picture.image && @picture.image.url%>
    <%= form.hidden_field :image_cache %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h3>以下の内容で、送信する。</h3>
    </div>
    <div class="picture_main_container">
      <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>

        <p>Content:<%= @picture.content %></p>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
        <%= form.hidden_field :image_cache %>
        <%= form.submit  "投稿する" %>
      <% end %>

      <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image_cache %>
        <%= form.submit "もどる", name: 'back' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>投稿編集</h1>
    </div>
    <div class="picture_main_container">
      <%= render 'form', picture: @picture %>

      <%= link_to '投稿詳細に戻る', @picture %> |
      <%= link_to '投稿一覧に戻る', pictures_path %>
    </div>
   </div>
 </div>

app/views/pictures/index.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>投稿一覧</h1>
    </div>
    <div class="picture_main_container">
      <table>
        <thead>
          <tr>
            <th>投稿者</th>
            <th>タイトル</th>
            <th>Image</th>
          </tr>
        </thead>

        <tbody>
          <% @pictures.each do |picture| %>
            <tr>
              <td><%= link_to(picture.user.name, user_path(picture.user.id)) %></td>
              <td><%= link_to(picture.title, picture_path(picture.id)) %></td>
              <td><%= image_tag picture.image, size: "75x50" %></td>              
            </tr>
          <% end %>
        </tbody>
      </table>

    <br>
        <%= link_to '新規投稿', new_picture_path, class:"operation_button" %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>新規投稿</h1>
    </div>
    <div class="picture_main_container">
        <%= render 'form', picture: @picture %>
        <%= link_to '戻る', pictures_path %>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>投稿詳細</h1>
    </div>
    <div class="picture_main_container">
      <p>
        <strong>投稿者:</strong>
        <%= link_to @picture.user.name, user_path%>
      </p>

      <p>
        <strong>タイトル:</strong>
        <%= @picture.title %>
      </p>

      <p>
        <strong>本文:</strong>
        <%= @picture.content %>
      </p>

      <p>
        <strong>画像:</strong>
        <%= image_tag @picture.image, size: "500x200" %>
      </p>

      <% unless @picture.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>

        <% else %>
          <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>

      <% if @picture.user_id == @current_user.id %>
        <%= link_to '投稿を編集する', edit_picture_path(@picture) %> |
        <%= link_to '投稿を削除する', picture_path(@picture), method: :delete, data: { confirm: 'Are you sure to delete your post?' } %> |
      <% end %>

      <%= link_to '投稿一覧へ戻る', pictures_path %>
   </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "") %> 件のエラーが発生しました:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email, id: :user_email, placeholder: "メールアドレス" %>
  </div>

  <div class="field">
    <%= f.text_field :name, id: :user_name, placeholder: "ユーザーネーム" %>
  </div>

  <div class="field">
    <%= f.password_field :password, name: "user[password]", placeholder: "パスワード" %>
  </div>

  <div class="field">
    <%= f.password_field :password, name: "user[password_confirmation]", placeholder: "パスワード(確認用)" %>
  </div>

  <div class="field">
    <%= f.file_field :user_image, id: :user_image %>
    <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url%>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>ユーザー編集</h1>
    </div>
    <div class="picture_main_container">
      <%= render 'form', user: @user %>

      <%= link_to '詳細画面へ戻る', @user %>
      <br>
      <%= link_to 'ユーザー一覧へ', users_path %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container">
  <!-- ユーザー詳細/上部 -->
  <div class="user-show">
    <div class="user-detail">
      <h3><%= @user.name %></h3>
      <div class="user-image">
        <% if @user.user_image? %>
          <%= image_tag @user.user_image.url, size: "210x210" %>
        <% else %>
          <%= image_tag("/user_images/default_user.jpg", size: "210x210") %>
        <% end %>
      </div>
      <p><%= @user.email %></p>
      <% if current_user.id == @user.id %>
        <p><%= link_to 'Edit', edit_user_path(@user) %></p>
      <% end %>
    </div>
  </div>

  <!-- ユーザー投稿一覧/お気に入りリンク -->
  <div class="user-tab">
    <ul class="user-tabs">
      <li><%= link_to "投稿一覧", user_path(@user.id) %></li>
      <li class="active"><%= link_to "お気に入り投稿一覧", "/users/#{@user.id}/favorites" %></li>
      <li><%= link_to "新規投稿", new_picture_path %></li>
    </ul>
  </div>

  <!-- お気に入り投稿一覧 -->
  <div class="posts-index">
    <ul class="row">
      <% @favorites.each do |favorite| %>
        <% picture = Picture.find_by(id: favorite.picture_id) %>
        <li class="col-md-4 col-sm-6">
          <%= link_to picture.title, picture %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="main">
  <div class="article">
    <div class="picrure_title">
      <h1>ユーザ一覧</h1>
    <div class="picture_main_container">
      <table>
        <thead>
          <tr>
            <th>Username</th>
            <th>User image</th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <tr>
              <td><%= link_to(user.name, user_path(user.id)) %></td>
                <% if user.user_image? %>
                  <td><%= image_tag user.user_image.url, size: "75x50" %>
                <% else %>
                  <td><%= image_tag "/user_images/default_user.jpg", size: "75x50" %>
                <% end %>
          </tr>
         <% end %>
        </tbody>
      </table>
     </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="article">
      <div class="lfloat">
        <img class="sign_img" src="/instagram_sign.jpg">
      </div>
      <div class="rfloat">
        <div class="form_container">
          <div class="form_container_top">
            <h3>Instagramclone</h3>
            <p>友達の写真や動画をチェックしよう</p>
          </div>
          <%= render 'form', user: @user %>
        </div>
        <div class="to_login_container">
          <p>アカウントをお持ちですか？　<%= link_to "ログインする", new_session_path %> </p>
        </div>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user-show">
    <div class="user-detail">
      <h3><%= @user.name %></h3>
      <div class="user-image">
        <% if @user.user_image? %>
          <%= image_tag @user.user_image.url, size: "210x210" %>
        <% else %>
          <%= image_tag("/user_images/default_user.jpg", size: "210x210") %>
        <% end %>
      </div>
      <% if current_user.id == @user.id %>
        <p><%= @user.email %></p>
        <p><%= link_to 'ユーザ情報編集', edit_user_path(@user) %></p>
      <% end %>
    </div>
  </div>
    <p><%= link_to "お気に入り", "/users/#{@user.id}/favorites" %></p>
    <p><%= link_to "新規投稿", new_picture_path %></p>
</div>